// src/atlas/tileAtlas.ts
// Auto-generated by scripts/compress-map.js (TILE=16, tiles laid in a single row)
// Ultra-compact: GIDs stored as a 2-char base36 stream; build {[gid]:[sx,sy]} once.
export const TILE=16;
export const tileAtlasMeta=(()=>{const T=TILE,S="0i0j0k1m1n1o1p1z20212324262g2h2i2k2l2m2x2y2z3132333q46484o5e5f5g5h5v5w5x6c";const M: {[key: number]: [number, number]}={};for(let i=0,j=0;i<S.length;i+=2,j++)M[parseInt(S.slice(i,i+2),36)]=[j*T,0];return M})();
